### PR TITLE
Remove multiple periods after traveler name

### PR DESCRIPTION
**Pull request by dwillis**
Some of the traveler names had multiple periods after them; I've added a line to the `clean_cell` method that removes these.

### CODE REVIEW

**Review by restrellado — APPROVED** [review]

**Review by hazel-bohon — COMMENTED** [review]
Line 64 is intended to remove the talking periods. It's probably missing some because of the $ symbol at the end which forces the query to match to the end if the string. I bet that we can combine line 63 and 64 to make a more robust solution.

**Comment by restrellado** [comment]
So I'm thinking one of two things: 

- I can merge the PR and then @zacherybohon can do another PR to combine lines 63 and 64. Or 
- @dwillis and @zacherybohon can take the conversation to Slack and have @dwillis do the change on this current PR

Do either of you have a preference? Sorry I can't help or comment more. R guy here! :)

**Comment by dwillis** [comment]
I'm happy to edit the PR. It looks like I can accomplish the same outcome by adding a `strip()` call in line 64, thus no need for line 63.

**Comment by restrellado** [comment]
@dwillis Great! I'll wait for it and will merge it as soon as it comes in. Thank you sir!

**Comment by dwillis** [comment]
Ok, take a look now @restrellado @zacherybohon

**Comment by hazel-bohon** [comment]
Very cool!

**Pull request merged**
